
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_LOGIN_STATE = 'RESET_LOGIN_STATE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const SET_FIELD_VALUE       = 'SET_FIELD_VALUE';
export const FORM_SET_FIELD_VALUE  = 'FORM_SET_FIELD_VALUE';
export const VALIDATE_FORM_FIELDS  = 'VALIDATE_FORM_FIELDS';
export const VALIDATE_SUCCESS      = 'VALIDATE_SUCCESS';
export const VALIDATE_FAILURE      = 'VALIDATE_FAILURE';
export const RESET_REGISTER_FORM = 'RESET_REGISTER_FORM';
export const REGISTRATION_REQUEST_START     = "REGISTRATION_REQUEST_START";
export const REGISTRATION_REQUEST_SUCCESS   = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_FAILURE   = "REGISTRATION_REQUEST_FAILURE";

/**
 * Dashboard action constants
 */

export const DASHBOARD_STATS_REQUEST = 'DASHBOARD_STATS_REQUEST';
export const DASHBOARD_STATS_SUCCESS = 'DASHBOARD_STATS_SUCCESS';
export const DASHBOARD_STATS_FAILURE = 'DASHBOARD_STATS_FAILURE';
export const DASHBOARD_UPDATE_STATS  = 'DASHBOARD_UPDATE_STATS';
/**
 * Side bar action constant
 * 
 */
export const SIDE_BAR_DISPLAY = 'SIDE_BAR_DISPLAY';
export const SIDE_BAR_SELECT_ITEM = 'SIDE_BAR_SELECT_ITEM';

